### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by nonrect** [PurityWasHere/OpenBullet-Anomaly-Plugin#1]
Hey

I literally enjoy this build and by knowing that it is becoming a plugin to use official OB's updates, It even become much better

I really feel the lack of "Config Encryption" feature, I know leaving config's open is generally good for everyone but sometimes we really need to lock one for some specific reasons

Thanks

**Comment by PurityWasHere** [comment]
I'm not sure exactly how I would do this through a plugin, especially a opensource plugin.
