### ISSUE TITLE
Reload proxy - Remote Address

### ISSUE THREAD

**Issue by nonrect** [PurityWasHere/OpenBullet-Anomaly-Plugin#2]
When we setup several runners with high number of threads, Internet speed becomes less stable

having said that, if we happened to enable "Reload proxy" check in settings, sometimes it cannot download the proxy from remote address (i.e: Proxyscrape) and returns an error "Could not contact the reload API" and if it happens 3-4 times, It completely stops the runners that couldn't get the proxy

More info:
https://forum.openbullet.dev/topic/542/openbullet-bug/5

Now is there a possibility to add a feature that if it couldn't download the proxy after several tries, use the previous list until the next try ? or improve the way it gets the proxy from the link ?

Because when you want to have a heavy load on your OB, avoiding this error is almost inevitable

**Comment by PurityWasHere** [comment]
This issue is being worked on internally by Ruri. It's not needed in a plugin
