### ISSUE TITLE
Selenium - Chrome problem

### ISSUE THREAD

**Issue by nonrect** [PurityWasHere/OpenBullet-Anomaly-Plugin#3]
When I run my selenium checker on 20 threads, It works perfectly fine but after several hours the number of "chrome.exe" and "chromedriver.exe" tasks will increase significantly which freezes my PC and makes me to restart it

I had to add a windows schedule to run a bat file every half an hour to kill all "chrome.exe" & "chromedriver.exe" tasks, I also know we have this options in "Tools" but it's not auto

Adding Feature Request:
• I wish you could add an ability to set "Selenium Tools" on auto (run every # minutes or run after a specific number of tries, or even maybe you can develop a better workaround for this)

**Comment by PurityWasHere** [comment]
Have you tried ticking always exit in your config settings? This should force chromedrivers to close

**Comment by nonrect** [comment]
Yes, I checked "Always Quit browser at the end" when I created the config

I tested the same config several times and on every test my VPS hangs the way that I have to restart it (5 Core, 5Ghz, 6GM RAM, Windows Server 216)

When sometimes I could reach to it before the full freeze, I could notice a huge number of "chrome.exe" and "chromedriver.exe" on my task manager and I was not able to run OB or some other programs because windows was giving me the error of "low RAM"

**Comment by PurityWasHere** [comment]
This seems like an internal issue with OB then. Please open an issue on the official OB GitHub and describe what you stated here
