### ISSUE TITLE
Separated Plugins

### ISSUE THREAD

**Issue by Unkn9wn1** [PurityWasHere/OpenBullet-Anomaly-Plugin#8]
Hi,

may u make separated plugins for each different functions or blocks?

and also may u write what is this AutoStart thing?
![image](https://user-images.githubusercontent.com/41063376/78729107-69f07e00-794e-11ea-872c-bc82f9a17427.png)

thank you

**Comment by PurityWasHere** [comment]
I'm not gonna split it up into separate Plugins, you can do that yourself easily using the source code. 
As far as what autostart is it's a form I made while expirementing on the change log / Update checker
