### ISSUE TITLE
Conversion of .anom to .loli

### ISSUE THREAD

**Issue by CallMeAldy** [PurityWasHere/OpenBullet-Anomaly-Plugin#9]
Converting .anom to .loli using the inbuilt method breaks the configs. They all get 0 hits.

**Comment by PurityWasHere** [comment]
Its a issue with your Environment file. Please Install the latest version of the plugin and go to Anomaly Extras. Then press Patch Environment. After that restart Openbullet and itll be fine

**Comment by CallMeAldy** [comment]
I have downloaded OB and Anomaly plugin again in a fresh environment, and now the master-worker is throwing out an error saying "Object reference not set to an instance of an object"
